### PR TITLE
Update deps for PS 0.14

### PR DESCRIPTION
**Pull request by oreshinya**
For 0.14

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]
👍 looks good to me! (I'm not a maintainer, though.) Verified I could build this and pass the tests locally.

You could also update the repository field to be:

```diff
- git://github.com/bodil/purescript-test-unit.git
+ https://github.com/bodil/purescript-test-unit.git
```

...to match the PureScript registry.

**Comment by thomashoneyman** [comment]
Once this merges the library will need a major version release to ensure folks using bower who depend on `test-unit` can update to PureScript 0.14 without using resolutions.

**Comment by thomashoneyman** [comment]
Hi @adamczykm -- I see you have the latest commit to this repository. Any chance you'd be able to give this a review?

**Comment by milesfrain** [comment]
I believe @bodil and @justinwoo are the current maintainers. I think this library is fairly widely used (or at least forks of it are). Would this library benefit from additional maintainers, or being part of of the purescript-contrib org?

**Pull request merged**
