### PR TITLE
[WIP] Add support for PureScript 0.9.1

### PR DESCRIPTION
**Pull request by paulyoung**
This is currently blocked by https://github.com/hdgarrood/purescript-sequences/issues/22 (which is subsequently blocked by https://github.com/purescript-node/purescript-node-fs#30)

### CODE REVIEW

**Comment by paulyoung** [comment]
Now waiting on https://github.com/hdgarrood/purescript-benchotron/pull/10 which is blocked by https://github.com/purescript-node/purescript-node-readline/pull/8

**Comment by romansergey** [comment]
@paulyoung, thanks for sorting this! both deps seem to be merged now. Shall we bump the bounds and merge this one?

**Comment by bodil** [comment]
Far as I can tell, ps-sequences doesn't have a new release yet?

**Comment by romansergey** [comment]
Oops, my apologies, haven't noticed that one :)

**Comment by paulyoung** [comment]
Yes, https://github.com/hdgarrood/purescript-sequences/issues/22 is still waiting on a purescript-benchtron release.

**Comment by kika** [comment]
I made it compile and pass tests here:
https://github.com/kika/purescript-test-unit/tree/purescript-0.9.1

It depends on my own update to `purescript-sequences`

**Comment by bodil** [comment]
If I recall correctly, it could also just be rewritten to use `purescript-lists` instead. I don't think there would be any performance impact, I've just tended to prefer `sequences` by default. I'll have a crack at it.

**Comment by paulyoung** [comment]
Thanks @bodil!

**Pull request closed without merging**
