### PR TITLE
Aff updates

### PR DESCRIPTION
**Pull request by natefaubion**
Aff 4 is still in RC, but it should be released soon.

### CODE REVIEW

**Comment by natefaubion** [comment]
Ugg, I forgot to pull. I'll close this and fix it up.

**Comment by natefaubion** [comment]
Is the merge commit too ugly? My git-foo isn't strong enough to rewrite the history.

**Comment by natefaubion** [comment]
Seems like the purescript version that Travis is using is old?

**Comment by natefaubion** [comment]
@bodil I've update `.travis.yml` to not use `next`, and the tests run and pass. @justinwoo seemed to indicate his tests didn't work when trying to use my branch, but I don't know the details, and if I might be missing something which the tests don't cover.

**Comment by justinwoo** [comment]
Sorry, the problem was with some shoddy FFI code 😿, Nate's branch seems to work fine

**Comment by bodil** [comment]
Seems to work fine here as well. I'll merge and release.

**Pull request merged**
